<?php
/**
 * Created by PhpStorm.
 * User: monsajj
 * Date: 29.09.2018
 * Time: 10:58
 */

namespace App\Facades;


use Illuminate\Support\Facades\Facade;

class Math extends Facade
{
    /**
     * Get the registered name of the component
     *
     * @return string
     */
    protected static function getFacadeAccessor()
    {
        //parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return 'math';
    }
}